---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-15.10
  - name: ubuntu-16.04

suites:
  - name: master
    driver:
      network:
        - ["private_network", {ip: "192.168.33.10"}]
    run_list:
      - recipe[prep::master]
      - recipe[postgres-replication::master]
      - recipe[prep::create_db]
    attributes:
      postgresql:
        config:
          listen_addresses: 192.168.33.10
        pg_hba:
          - type: host
            db: replication
            user: repuser
            addr: 192.168.33.11/32
            method: md5
  - name: slave
    driver:
      network:
        - ["private_network", {ip: "192.168.33.11"}]
    run_list:
      - recipe[prep::slave]
      - recipe[postgres-replication::slave]
    attributes:
      postgresql:
        config:
          listen_addresses: 192.168.33.11
      postgres-replication:
        master:
          ip: 192.168.33.10
